services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: client.dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ./client:/app        # <-- add this
      - /app/node_modules     # <-- ignore node_modules from host
    develop:
      watch:
        - action: sync
          path: ./client:/app
          target: /app
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:4000
          
  backend:
    container_name: backend
    image: backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports: 
      - "4000:4000"
    volumes:
      - ./backend:/app        # <-- add this
      - /app/node_modules     # <-- ignore node_modules from host
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
